### ISSUE TITLE
Support create-env to normal bosh manifests

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#118]
In the scenario below, I am targeting a bosh that was deployed on another bosh, rather than a bosh deployed by `bosh-init`. Could we support `bosh create-env` for this scenario too?

```
$ bosh2 create-env bosh-lite-48-drnic-dpg.yml
Deployment manifest: '/Users/drnic/Projects/bosh_deployments/snw-deployments/bosh-lites/bosh-lite-48-drnic-dpg.yml'
Deployment state: '/Users/drnic/Projects/bosh_deployments/snw-deployments/bosh-lites/bosh-lite-48-drnic-dpg-state.json'

Started validating
Failed validating (00:00:00)

Parsing installation manifest '/Users/drnic/Projects/bosh_deployments/snw-deployments/bosh-lites/bosh-lite-48-drnic-dpg.yml':
  Validating installation manifest:
    - cloud_provider.template.name must be provided
    - cloud_provider.template.release must be provided
    - cloud_provider.template.release '' must refer to a release in releases
```

BTW, I'm assuming that `bosh create-env` the replacement for `bosh target URI ALIAS`? If not, sorry.

**Comment by drnic** [comment]
I think I guessed wrong (omg so much guessing as to how to use bosh2 for a long time bosh1 user). `bosh2 create-env` isn't to setup a target; that's `bosh2 alias-env` I think https://bosh.io/docs/cli-v2.html

**Comment by cppforlife** [comment]
create-env is just renamed bosh-init deploy. its been augmented with -o, -v, etc flags.

re deploy bosh with bosh. it's possible though thru a regular bosh deploy command (i do this for my env when playing with diff features). here is an example from bosh-deployment repo: https://github.com/cloudfoundry/bosh-deployment/blob/master/test.sh#L99 (though bosh deploy instead of bosh interpolate). prolly should rename bosh-dev.yml to something else.

docs for v2 are coming...
