### ISSUE TITLE
CLI doesn't warn you if interpolated variables can't be resolved

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-cli#13]
If I specify an interpolated variable in my manifest (e.g. `some_field: ((my_var))`) but fail to provide that value via the `-l` or `-v` flag, I'd expect the CLI to warn me. The `fly` CLI throws the helpful error `unbound variable in template: 'my_var'`. In the current BOSH CLI, you get random errors 10 minutes later: `dial tcp: lookup ((external_ip)): invalid domain name`.

**Comment by dpb587-pivotal** [comment]
Is this with the `deploy` command or `create-env`?

With `deploy` it's intentional because director may end up resolving the values via config server. Which is kind of weird, ambiguous behavior because of scenarios like you're describing. And a bit weird IMO - now you must know if your director is configured for config-server.

With `create-env` it's probably a good idea to error if we don't already since we won't be supporting anything else interpolating them.

**Comment by ljfranklin** [comment]
> Is this with the deploy command or create-env?

This was with `create-env`. The `deploy` + config server example makes sense, although we should probably make sure we fail as quickly as possible on interpolation errors in that case as well.

To add a bit more context, I'm trying to interpolate some director secrets (e.g. passwords) and a separate file for the terraform outputs (e.g. IP addresses):

```
bosh create-env \
    -l <(echo "${BOSH_DIRECTOR_SECRETS}") \
    -l "${terraform_config}/metadata" \
    ./director.yml
```

**Comment by cppforlife** [comment]
agreed that for create-env it should raise an error. deploy is on purpose.

**Comment by cppforlife** [comment]
Fixed in https://github.com/cloudfoundry/bosh-cli/releases/tag/v0.0.87.
