### ISSUE TITLE
delete-deployment should fail if deployment does not exist

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/bosh-cli#141]
This seems like unexpected behavior:

```
bosh delete-deployment -n -d this-deployment-doesnt-exist
Using environment 'https://192.168.11.2:25555' as client 'admin'

Using deployment 'this-deployment-doesnt-exist'

Succeeded
```

```
bosh -v
version 2.0.5-ec671ee-2017-02-18T01:11:19Z
```

**Comment by tylerschultz** [comment]
I've had this discussion w @cppforlife in the past. The justification is that a step in a CI should not fail because there is nothing to delete. He'd like it idempotent. I see that point, but I've also seen a lot of complaints going the other way, which I can sympathize with too. DK, what if this command were only succeed when the deployment is missing if a flag was specified. Like `rm -f no-such-file`?

**Comment by tjvman** [comment]
I'd like a `-f` flag or at least some output that indicates that nothing was actually deleted so that users don't have to run `bosh deployments` to confirm that the operation did something

**Comment by benmoss** [comment]
Yeah, every other command in the world has a `-f` flag for this kind of use-case, I don't see why this should be any different

**Comment by dpb587-pivotal** [comment]
Closing in favor of https://github.com/cloudfoundry/bosh/issues/2053 - lets consolidate future discussion there.
