### ISSUE TITLE
automating/scripting log-in

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#167]
It's a new world, and `admin`/`admin` isn't a great username/password combo. So the username + password are different.

How can we script `bosh log-in` to pass in the user/password?

In v1, we had `bosh login username password`, for example.

**Comment by tjvman** [comment]
`bosh login-in --client=FOO --client-secret=BAR` would be one option. You can also use the `BOSH_CLIENT` and `BOSH_CLIENT_SECRET` environment variables if you don't want to use the command-line flag. 

Worth mentioning that the flags take precedence over the env vars.

**Comment by drnic** [comment]
Awesome, thanks.

**Comment by cppforlife** [comment]
Here is an example from our CI script: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/blob/master/ci/tasks/deploy-director.sh#L41

Idea is that you just need to provide BOSH_CLIENT and BOSH_CLIENT_SECRET (regardless if it's basic or UAA auth), and then run any command. cli will just pick it up.

We also dont want to hard code to username/password because UAA technically can be asking variety of prompts (like one time code, etc.)

**Comment by drnic** [comment]
Thanks @cppforlife

**Comment by emperorente** [comment]
@cppforlife , is the example only worked for v2? @drnic，how can I automate login use scripts? use the user/name or client/client_secret
