### ISSUE TITLE
Discover available links

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#186]
Is there/or could there be a way to discover what links have been provided (and their properties) by a deployment/all deployments?

**Comment by drnic** [comment]
I see that `bosh2 insr nats/16` returns some links information. Could the provided links properties be included too?

**Comment by cppforlife** [comment]
@drnic re --json: yeah currently, we dont export values based on their type. everything always gets converted to strings in the env. something for us to improve on. 

re links discovery: i was thinking to introduce `bosh -d foo links` at some point to be able to see the tree (who provides, who consumes, etc.); not sure how it should be presented to the user though.

cc @pivotal-jamil-shamy

**Comment by pivotal-jamil-shamy** [comment]
@cppforlife @drnic I like `bosh -d foo links` , though it would tricky to display it in a meaningful way to the user.

Since a `job` consumes/produces a link, simply listing all the running jobs ( in a table format ) with the links they provide and consume would be the first thought. 

But looking at it closely, we can have a job that is deployed in multiple instance groups, and each one of these jobs can consume different links. For example, having a job in an instance group consuming an optional link as `nil` or as some other alias, which might not be the case for another instance of the job in a different instance group.
 
So we are left with listing the links per job per instance group, which looking at a deployment like `cf` can get very complicated quickly.

Maybe a long shot, or out of the scope of the CLI, might be nice for the CLI to output some generic dependency graph represented in JSON and then another UI tool (some javascript library maybe) to display it. Since it feels it is more of a visualization issue here.

**Comment by geofffranks** [comment]
+1

**Comment by mfine30** [comment]
cc @freddesbiens to prioritize appropriately
