### ISSUE TITLE
just running "bosh" should not exit 1

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/bosh-cli#188]
The bosh command should run and print out the "help" instead of exiting 1 and asking you to specify a command. This is basically the old behavior from bosh v1. Even not printing the help and just listing commands but not exiting 1 would be way better.

**Comment by dpb587-pivotal** [comment]
It might be a bit subjective, but I disagree. The `bosh` binary, without a subcommand, has no inherent purpose so it should not exit successfully.

That behavior is also a bit defensive which helps in external tooling - if a user/script accidentally leaves off its intended command, it will error - error being better than scripts continuing with invalid state.

It does currently provide some hints that you're attempting to use `bosh` incorrectly when it dumps out the long, one-liner of commands. Output from commands should be as succinct as necessary, and I don't think we should be outputting pages of data just because the invocation was incorrect (see #103). I think the old bosh cli behavior in this regard was incorrect.

Out of curiosity, in what cases are you executing `bosh` where you care about the exit code when an argument is not passed?

**Comment by cppforlife** [comment]
agree with danny. this would not be typical unixy behaviour (even though it was old cli behaviour).
