### ISSUE TITLE
logs command should immediately fail when no argument given

### ISSUE THREAD

**Issue by davidjahn** [cloudfoundry/bosh-cli#197]
Current behavior of `bosh logs`: when you do not specify a VM to get logs from, the cli makes a call to the director and gives a not-useful error:

```
$ bosh -d my-deployment logs
Using environment 'https://my-director:25555' as client 'some-user'

Using deployment 'my-deployment'

Fetching logs:
  Director responded with non-successful status code '404' response '{"code":70001,"description":"No instances matched {:uuid=>\"*\", :deployment_id=>28}"}'

Exit code 1
```

The CLI should probably fail immediately with a useful error message rather than making an invalid request to the director, eg:

```
$ bosh -d my-deployment logs
error: must specify VM for logs
<usage info>
...
```

**Comment by dpb587-pivotal** [comment]
It is a rather vague error response, but in this case, it's because you're not on a recent enough director for this to work – newer directors ([v260+](https://github.com/cloudfoundry/bosh/releases/tag/v261)) do support gathering logs from all instances. To match behavior on a few other commands (like `ssh`), we decided to make the instance/id argument optional with the assumption users will be on new enough directors soon enough and not have to worry about this error in the future.

Seem like a reasonable explanation?
