### ISSUE TITLE
If target director does not have config-server, then fail fast if missing --vars-store

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#200]
With `bosh deploy` either the target director has a config-server or the user needs `bosh deploy manifest.yml --vars-store path/to/creds.yml`. Can we please fail fast with a nice error message?

In writing articles/docs, I'm unsure what path to take at the moment - to include `--vars-store` in all examples in case they don't have config-server/credhub, or to future proof the articles by not including `--vars-store` on the assumption that one day they will have it.

It would help if the CLI fail nicely and helpfully and fast if `--vars-store` was missing but it was required because there was no config-server/credhub.

**Comment by mkuratczyk** [comment]
Kind of related to that - I just had the opposite situation where the CI script contained --vars-store but the Director now uses Credhub. In this scenario the outcome is - credentials are generated twice (by the CLI and Credhub) but the credentials generated by CLI and stored in vars-store are actually used. It's very confusing because I have credentials generated and stored in Credhub but they don't work. This should also fail fast or, if CLI intentionally takes precedence, config server should not generate credentials at all.

**Comment by mfine30** [comment]
This does seem like an interesting use case and area for improvement. Closing/re-opening to make a Tracker story.

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty
