### ISSUE TITLE
UAA unknown issuer error

### ISSUE THREAD

**Issue by ssurenr** [cloudfoundry/bosh-cli#219]
When trying to connect a bosh director with UAA authentication bosh-cli complains about unknown issuer even after providing the RootCA

```
$ bosh2 -e bosh-dev.sys.np.covapp.io log-in --ca-cert=/Users/suren/Downloads/intermediate_chain.pem
Requesting UAA prompts:
  Performing request GET 'https://uaa.covisintrnd.com:443/login':
    Performing GET request:
      Retry: Get https://uaa.covisintrnd.com:443/login: x509: certificate signed by unknown authority

Exit code 1
```

However, all intermediate as well as root certificates are provided and it is verifying perfectly.
```
$ openssl verify -CAfile /Users/suren/Downloads/intermediate_chain.pem uaa.crt 
uaa.crt: OK
```

**Comment by dpb587-pivotal** [comment]
@cppforlife, I think we should be using [`AppendCertsFromPEM`](https://golang.org/pkg/crypto/x509/#CertPool.AppendCertsFromPEM) instead of [`AddCert`](https://golang.org/pkg/crypto/x509/#CertPool.AddCert) both [here](https://github.com/cloudfoundry/bosh-cli/blob/b66cf70abee1dcb323a8f6b7f5234879ede4e024/uaa/factory_config.go#L94-L108) and [here](https://github.com/cloudfoundry/bosh-cli/blob/25e263f44763a85339a5908400a55107094dad41/director/factory_config.go#L92-L106).

**Comment by cppforlife** [comment]
@ssurenr seems like we are not picking up all of the necessary certs. story: https://www.pivotaltracker.com/story/show/145311531

**Comment by ssurenr** [comment]
Is there any work arounds that you can suggest?

**Comment by cppforlife** [comment]
new version of cli (https://bosh.io/docs/cli-v2.html#install) should be able to use intermediate certs.
