### ISSUE TITLE
Validation of existing final build index entries

### ISSUE THREAD

**Issue by jamesjoshuahill** [cloudfoundry/bosh-cli#251]
### What

Please could we add a validation of entries in `.final_builds/**/**/index.yml` files by the CLI to improve the error message when an existing entry is invalid. For example, when `blobstore_id` is missing from an entry.

### Steps to reproduce

- In a bosh release that has a final build of a job without a `blobstore_id`. For example: https://github.com/pivotal-cf/cf-redis-release/blob/0f8a34884242555bdc440cea47aa6189eaa3662e/.final_builds/jobs/broker-deregistrar/index.yml#L7-L9
- `bosh -n create-release --final`
- See an internal inconsistency error message like this one:
```
Failed adding job 'broker-deregistrar/dd5fbe93b23aa21a61b0edfbb25b3851f44ed5b3d41b4e564a9959b77aeafe0e'


Internal inconsistency: entry must include blob ID 'index.indexEntry{Key:"11a29e6660b1494d4acea088708327d0773f2ead", Version:"11a29e6660b1494d4acea088708327d0773f2ead", BlobstoreID:"", SHA1:"60b2b364edd59bcb86b61a6b83a47e7bff7afdcb"}'

Exit code 1
```

### Why

Because this error message did not indicate the cause of the error and it took a long time to understand. The [error arises](https://github.com/cloudfoundry/bosh-cli/blob/105157c38524ddbb8367c868afa06eb00f285125/releasedir/index/fs_index.go#L238) during the upload of blobs to the bosh release blobstore. The proposed validation could be done at the start of `create-release` process.

### How we fixed it

We added dummy `blobstore_id` properties to the invalid entries to satisfy the existing bosh CLI validations: https://github.com/pivotal-cf/cf-redis-release/commit/caacfe1a6ba7ba74b86d71a65aa8c4969328013a

cc @cppforlife @ferozjilla

**Comment by cppforlife** [comment]
interesting final builds record...

> Because this error message did not indicate the cause of the error and it took a long time to understand. The error arises during the upload of blobs to the bosh release blobstore.

any suggestion for the error message?

>  The proposed validation could be done at the start of create-release process.

wasn't the error already thrown in the create-release process?

**Comment by jamesjoshuahill** [comment]
Hi @cppforlife!

Indeed, we don't know how those final builds with no `blobstore_id` were created 😕 This issue may affect other release authors who cut final releases with the ruby bosh CLI.

We would like the error message to include:
- indication that the error was caused by an existing entry in the index, not a new entry being saved during `bosh create-release --final`.
- filename of the index that contains the invalid entry.
- details of the invalid entry to help find it.

For example:

```
Invalid index: missing blobstore_id for entry 11a29e6660b1494d4acea088708327d0773f2ead in '.final_builds/jobs/broker-deregistrar/index.yml'.
```

We think this error could be raised when entries are read from an index file. For example, before the `FSIndex#entries` function returns entries https://github.com/cloudfoundry/bosh-cli/blob/105157c38524ddbb8367c868afa06eb00f285125/releasedir/index/fs_index.go#L227.

Would you accept a PR?

**Comment by dpb587-pivotal** [comment]
I don't think error checking should occur in `entries`. Since it is used for read operations, that would mean that any user trying to recreate a release from a broken repo like cf-redis-release (or even from an old tag) would experience this error, and they probably would have even less of an idea about how to fix it as a non-release author.

Minor detail... but technically the error could be occurring while saving the file to a different location than it was originally read. If/when that's the case, the file name in the error message might be even more misleading.

I'm not sure of a better error message. Personally, I find the error message sufficiently informative of the very strange exception. But I'm probably biased.

For what it's worth, you should remove those entries from the `.final_builds`. Neither ruby nor golang CLI would be able to recreate releases trying to reference those blobs (looks like at least v147 and v148 are affected).

**Comment by freddesbiens** [comment]
Hi. 

I must say I agree with the arguments above. For this reason, I will close the issue for now. However, if you do run into the issue where your new final releases have missing `blobstore_id`, please open an issue so we can investigate.
