### ISSUE TITLE
Concurrent create-env commands in separate directories do not work

### ISSUE THREAD

**Issue by dprotaso** [cloudfoundry/bosh-cli#267]
One of them will fail
See https://github.com/cloudfoundry/bosh-bootloader/issues/161

**Comment by dpb587-pivotal** [comment]
Parallel create-env commands which both use the ssh tunnel / registry currently do not work since the registry listener is hard-coded for 127.0.0.1:6901 ([source](https://github.com/cloudfoundry/bosh-cli/blob/1f8ec439c59fa5451bd6ad5f8923b9ea9a84755c/installation/manifest/parser.go#L133)).

I think users are typically able to avoid this this since most automated/parallel uses end up running from Concourse/CI in their own containers.

It seems like the local port could be dynamically allocated though - I don't think there's a particular reason it must always be running on 6901.

**Comment by cppforlife** [comment]
@dprotaso it's currently challenging to make this port configurable as it's used in all kinds of tunneling code through the bosh-agent. how often do you run into this problem? mostly aws?

**Comment by freddesbiens** [comment]
@dprotaso Is this still an issue you care about? We can have a deeper look but need to know more.
