### ISSUE TITLE
bosh cli hangs when the ca cert used by the cli doesn't match that of the director

### ISSUE THREAD

**Issue by dprotaso** [cloudfoundry/bosh-cli#268]
I would expect it to fail quickly - but it hangs.

**Comment by dprotaso** [comment]
```bash
$ bosh -v
version 2.0.28-cb77557-2017-07-11T23:04:15Z
```

**Comment by dprotaso** [comment]
Commands I ran were `vms` and a `deploy`

**Comment by dpb587-pivotal** [comment]
Can you verify you're contacting the director you expect? Hanging behavior sounds closer to hitting a black hole IP, rather than incorrect CA cert.

When CA cert is incorrect, it currently results in the following error and does not hang...

```
Fetching info:
  Performing request GET 'https://192.168.50.6:25555/info':
    Performing GET request:
      Retry: Get https://192.168.50.6:25555/info: x509: certificate signed by unknown authority

Exit code 1
```

For more information and to verify the endpoint being used, you may want to try `BOSH_LOG_LEVEL=debug bosh env`.
