### ISSUE TITLE
I want to pass a directory or wildcard to the -o flag

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-cli#287]
We keep all the ops files for a given environment in the same directory. In order to generate a manifest I currently have to provide an `-o` flag for each one. I want to provide and `-o` flag once with a path to this directory.

**Comment by drnic** [comment]
If you need all the patches all the time can all the patches go into a single file?

________________________________

**Comment by shalako** [comment]
The team finds it easier to manage separate ops files for different features. Not all environments have the same features deployed.

**Comment by drnic** [comment]
@shalako so you're ok with explicit `-o this-feature.yml -o and-this-one.yml` to pick out the ones you want?

**Comment by eljuanchosf** [comment]
+1 on the wildcard request.
Some teams manage separate ops files for each feature, which allows better organization and readability. However, if you manage many ops files, the CLI arguments can become hard to read and manage as well. A wildcard can be extremely useful.

**Comment by aeijdenberg** [comment]
One challenge might be that the order in which ops files are processed can result in different results. e.g. if 2 ops files replace the same field with different values, then the order in which they are processed matters.

It's not clear to me that there's a obvious deterministic order in which wildcard filename matching should be done...

**Comment by aeijdenberg** [comment]
By the way, I think some shells (e.g. bash) can do this for you, and I think define the order as alphabetical, e.g.:

```bash
#!/bin/bash

bosh deploy -o <(cat ops/*.yml) ...
```

**Comment by eljuanchosf** [comment]
I agree that a "wilcarded" execution list order can be confusing, but since the philosophy behind many BOSH features is driven by "convention over configuration", an alphabetical ascending order could be defined for the ops file list. With the adequate documentation, I believe it should be clear enough.

**Comment by shalako** [comment]
As I don't expect the ops files we use to modify the same properties, I don't care about order. If they do overlap, I expect to have to troubleshoot.

@drnic No I'm not ok with picking out the ones I want. Each of our environments has a directory containing ops files. I just want to refer to the directory. Support for directories and wildcards is one reason why, as a consumer of a release, manifest generation scripts are still easier to use.

**Comment by aegershman** [comment]
Not trying to legitimately resuscitate, but I came across this issue & figured I'd share some similar ideas:

I'm a fan of [`helmfile`](https://github.com/roboll/helmfile#single-directory), which is a tool to declaratively define/control multiple helm charts. You can pass in a directory containing helmfile manifests and it'll apply them in lexigraphical order. Like what ctaymor said above, in order to get ordering, you just prepend the files with `00-foo.yml`, `01`, etc.

Alternatively, `kubectl apply --kustomize <directory>/` does something kind of similar, but it looks for [a `kustomization.yml` file in the directory](https://kubectl.docs.kubernetes.io/pages/app_management/apply.html) which defines ordering and other things... Not quite the same situation as ops-files in a directory, but an interesting implementation. Especially if something similar to this [`bosh-init`](https://github.com/cloudfoundry/bosh-notes/issues/49#issue-371671637) issue were to come to fruition. There might be some interesting ideas from `--kustomize` to borrow.

---

Anyway, the point is, there are examples of other tools doing something similar to this idea.
