### ISSUE TITLE
Reference array elements with bosh interpolate

### ISSUE THREAD

**Issue by gdenn** [cloudfoundry/bosh-cli#288]
Hi, using this feature https://bosh.io/docs/cli-int.html of bosh cli v2 i want to be able to pick specific values from an yml array like so:
`(( some_array[0].password ))`

```
some_array:
  - value1:
       password: 'foobar'
```
I couldnt find anything that covers this use case in bosh cli version 2. My current workarround is to copy paste by hand.

**Comment by dpb587-pivotal** [comment]
Hi - looks like path syntax is documented in the [Ops file page](https://bosh.io/docs/cli-ops-files.html#path) which should hopefully answer a few more questions.

For your particular example, `((some_array/0/password))` should work.

@cppforlife, I wonder if path should be documented in its own page (since vars/ops can be done independently).

**Comment by dpb587-pivotal** [comment]
Oops, sorry, I was confusing ops paths with variable paths, so that recommendation does not work.

It's not currently possible to access an element of an array, only hashes. The variable reference syntax is fairly basic since values may be stored in either local files (e.g. with `bosh create-env`) or external config servers (e.g. CredHub) and they're assumed to be structured as hashes.

In this particular case, do you have an example or rationale on why it's better to store values in an array instead of independent variable entries? If you're able to hard-code indices in the variable path, it seems like they also could/should be separate.

**Comment by gdenn** [comment]
One of the use cases is that we have a file which we use to configure our deployment landscape for a specific IaaS like bosh-lite. These iaas-files declare an array of stemcells which can be used by the services. In a service manifest i want to reference one of these stemcells out of the array using the bosh interpolate (( )) syntax. 

Furthermore i want to be able to select an entry of the array depending on its value like i can in ops files.

Maybe something like this:
```
(( iaas.stemcells/alias=ubuntu-trusty.version ))
```

This should let me search the array entry with alias=ubuntu-trusty in iaas.stemcells and return the version. 

There are a lot of situations where we need this kind of bosh interpolate referencing right now. Currently we overcome the problem by partially inserting the values in the manifests by hand.

Since our complete framework depends on a specific iaas-config file format we cannot fix the problem by making it independent variables without breaking the policy.

**Comment by dpb587-pivotal** [comment]
I might recommend the approach that [cloudfoundry/bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) takes - IaaS-specific settings are split by directories. The bosh-deployment uses ops-files (which is another option), for example, the [AWS CPI](https://github.com/cloudfoundry/bosh-deployment/blob/master/aws/cpi.yml#L10-L14) will patch in stemcells. But, if you want to use variables, I'd recommend `iaas.stemcells.ubuntu_trusty.version` (rather than trying to use key-filter syntax).

**Comment by tophat8855** [comment]
We have a use-case where we want to use an array of hashes in one place, and then supply the value of one key within the first hash to another place.

Specifically, we want cloud_controller's `application_domains` to be:
```
- name: example.com
- name: example.org
```
but we also want smoke_test's `application_domain` to be `example.com`.

We'd like to be able to say `application_domains: ((application_domains))` in the first case, and something like `application_domain: ((application_domains.[0].name))` in the second case.

As it is, we'll have to ask the user to supply a separate duplicate value for the smoke_tests.
