### ISSUE TITLE
upload-release fails on Windows machine with home directory starting with a number

### ISSUE THREAD

**Issue by theozaurus** [cloudfoundry/bosh-cli#305]
Hi,

When running on Windows:

```
bosh2 -e <the env> upload-release <the release>
```

We get the error

```
Extracting release:
  Shelling out to tar:
    Running command: 'powershell tar --no-same-owner -xzf <the release> -C C:\Users\439\.bosh\tmp\bosh-release190507123', stdout: '', stderr: '/usr/bin/tar: C\:\\Users#9\\.bosh\tmp\bosh-release190507123: Cannot open: No such file or directory
/usr/bin/tar: Error is not recoverable: exiting now
':
      exit status 1

Exit code 1
```

It looks like the Users\439 part is getting turned into Users#9. The number 43 in octal corresponds to '#' in ASCII so it looks like this is an escaping issue of some kind. 

The expected behavior is to successfully extract the archive and upload the release.

Thanks,

Theo

**Comment by Fydon** [comment]
@theozaurus That error is because the folder containing `tar.exe` isn't in your `PATH` environment variable. Use [BSD tar from bosh-agent][2], as the tar that comes with Git for Windows (`usr\bin` folder off the installation) requires building your own release of bosh with [this][1] pull request added to it.

[1]: https://github.com/cloudfoundry/bosh-utils/pull/11
[2]: https://github.com/cloudfoundry/bosh-agent/blob/master/integration/windows/fixtures/tar.exe

**Comment by theozaurus** [comment]
Thanks for the hint @Fydon. I've installed BSD Tar and it now works. The error message really doesn't suggest that BSD Tar is required!
