### ISSUE TITLE
Proposal: `bosh update` & `bosh update-env`

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#326]
Currently when we run `bosh deploy` or `bosh create-env` the collection of flags + input file locations is not cached. This means that to upgrade we must recreate the exact same commands used to originally create the deployment/env.

Instead, I propose that we cache the flags + file locations that were used to most recently deploy/create-env; and we add `bosh update` and `bosh update-env <name>` commands. These are effectively wrappers around `bosh deploy` and `bosh create-env`, preceded by changing to the original working directory and reusing the same flags.

**Comment by drnic** [comment]
`bosh upgrade` and `bosh upgrade-env` are alternate name ideas - this would match the `brew upgrade` and `apt-get upgrade` commands

**Comment by drnic** [comment]
Similarly `bosh delete-env` could reuse all the original template locations without the operator having to reconstruct a valid `bosh delete-env` command.

**Comment by evanfarrar** [comment]
I wholeheartedly support the idea of making environments a little more CRUD-like in the BOSH cli. But I have been wrestling with some of these same notions, with the hope of eventually integrating BBL-like functionality into the CLI itself. So I ask here the questions I have been unable to answer on my own:

1. Why does delete-env need anything more than a state file anyway?  It's quite frustrating to supply ops files and vars files which have no effect on the CPI calls which would be needed to tear down a bosh environment. I suggest that we should be able to omit as many needed args from delete-env as possible, independent of this suggestion.
2. Where would this be cached? In the state file? In ~/.bosh with the environment info? This is difficult for me, because I want `bosh envs` to be always in sync with this, but I also want the artifacts from bosh create-env to always be stored along with the commands that created them, so I'm split between those two options.
3. Is there any situation where the "cache" needs to be invalidated? What if I delete an ops file from bosh-deployment or, say, git pull deletes it, and then run `bosh update`.
4. If all the arguments are the same, why would I want to run it? I assume so that I can pass _more_ args, but then we'll almost certainly hit the cache invalidation issue. e.g What if your ops files need to apply in a specific order to work? What if you want to remove an ops file? Or remove a variable that is now unused?
5. How could I see what the arguments I originally created with are? If, say, I wanted to make another director like the one I had, or see what is different about two directors?

**Comment by cppforlife** [comment]
im of a quite different opinion on this topic. proposed command would be quite mysterious since it's not clear what inputs are going into it: which ops files, which directory for bosh-deployment, how do i add a config, how do i remove, etc.

what i've been recommending to people is to simply save their create-env and delete-env invocations into a bash script that they can always reference. not too much indirection and always clear what cli is going to act on. then create per director directory so that it's easy to manage them.

from a sec perspective, i would hope that these commands dont cache my variety of credentials in unknown places.

i dont think we can farily compare this to brew since it doesnt need to manage multiple copies, configs, or creds.

**Comment by cppforlife** [comment]
> what i've been recommending to people is to simply save their create-env and delete-env invocations into a bash script that they can always reference.

may be that's worth adding that to a guide

**Comment by zmb3** [comment]
> what i've been recommending to people is to simply save their create-env and delete-env invocations into a bash script that they can always reference.

I agree with this approach and have seen it work well.
Of more importance to me personally is the issue raised by @evanfarrar :

> Why does delete-env need anything more than a state file anyway? It's quite frustrating to supply ops files and vars files which have no effect on the CPI calls which would be needed to tear down a bosh environment. I suggest that we should be able to omit as many needed args from delete-env as possible, independent of this suggestion.

It's a major pain to keep the "delete-env" script up to date with the create script.  I would love to see this experience improve.

**Comment by cppforlife** [comment]
> Why does delete-env need anything more than a state file anyway? It's
quite frustrating to supply ops files and vars files which have no effect
on the CPI calls which would be needed to tear down a bosh environment. I
suggest that we should be able to omit as many needed args from delete-env
as possible, independent of this suggestion.

we dont necessarily know how your ops files are modifying entirety of the
manifest. eg bosh-deployment has cpi specific ops files that add
appropriate cpi configuration.

one future possibility we ve entertained is to separate cpi config, cloud
config and manifest for create-env as well. in this case you would only
need cpi config and state file. there are pluses and minuses to this
approach as well.

**Comment by cppforlife** [comment]
i would recommend for bbl to accept exact same arguments every time
regardless if it is running for the first or second time. i definitely had
problems with hidden state being not obvious when using bbl.

> This is actually very similar to the direction BBL is currently headed:
the create-env call will be a script in your state directory.

for bbl to expose that feels somewhat leaky. why does user of bbl need to
see this. can they modify it, will it be overriden. etc. becomes quites
complex.

**Comment by evanfarrar** [comment]
> i would recommend for bbl to accept exact same arguments every time
regardless if it is running for the first or second time. i definitely had
problems with hidden state being not obvious when using bbl.

I agree hidden state is very troublesome, but if introspection of state can be made intuitive and discoverable then I believe we can make that state feel like it has object permanence: read the state, write the state, update the state, delete the state.

If bbl made you remember all of the particulars of every environment then BBL would be plagued _exactly the problem raised in this issue_.

> for bbl to expose that feels somewhat leaky. why does user of bbl need to
see this. can they modify it, will it be overriden. etc. becomes quites
complex.

They can modify it. It will sometimes be overwritten. It _is_ quite complex. But I'd rather the tool deal with complexity than hope that my brain can do it reliably every time. I'd rather users be mad at my tool sometimes than be mad at themselves all the time while using my tool. The former we can ask forgiveness for, the latter results in users quietly leaving your ecosystem out of embarrassment.

**Comment by cppforlife** [comment]
> They can modify it. It will sometimes be overwritten. It is quite complex. But I'd rather the tool deal with complexity than hope that my brain can do it reliably every time.

that introduces multiple paths that user has to reason about (install vs update). they need figure out initial set of args, and then on subsequent installs they need to figure out something different. i think this goes against most of the tooling we typically use (bosh, concourse, terraform, cloudformation, etc.) which is surprising imho.
