### ISSUE TITLE
alias-env to cache gateway flags

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#331]
Currently we can setup env vars which `bosh ssh` will use. Could we please configure and cache these values with `bosh alias-env`, so that simply selecting an environment will encourage `bosh ssh` to use the corresponding gateway config?

**Comment by cppforlife** [comment]
@drnic do these options help: http://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=263.3.0#p=director.default_ssh_options ?

**Comment by drnic** [comment]
And the ssh certificate? Can it be cached as part of targeting an environment; rather than an explicit extra local file (which must also be made private and placed in a private folder) and setup with an additional env var?

________________________________

**Comment by drnic** [comment]
BTW, thx for reminder of Director config for the other options; which reminded me of the remaining local aspect of the gateway - the ssh certificate (which is now being generated by bosh create-env and stored in a local creds.yml file)

________________________________

**Comment by dpb587-pivotal** [comment]
SSH certificate? Not sure what that means. The target VM's public host key is automatically sent to the ssh client and will verify that. When using SSH key authentication for the gateway VM, the gateway host key is ignored altogether (safe since the raw credential is never sent to the server, and host verification is still performed for the actual, target vm). Have you seen a particular error?

**Comment by evanfarrar** [comment]
I believe @drnic means the SSH private key for the gateway host.

@dmitriy @drnic Director config is nifty, but not very helpful with this unless I am missing something that persists that with alias-env from the API. How did one _get_ the `default_ssh_options.gateway_host` if the director API is behind that same gateway? This won't help, unless you are suggesting that the BOSH API be exposed...publicly?

**Comment by drnic** [comment]
@dpb587-pivotal sorry I meant SSH private key

Currently I have to set up lots of env vars which are all coupled to the same environment:

```
export BOSH_ENVIRONMENT=bosh-lite-10
export BOSH_GW_USER=jumpbox
export BOSH_GW_HOST=10.213.13.10
export BOSH_GW_PRIVATE_KEY=~/Projects/bosh_deployments/snw-deployments/bosh-lite-deployments/bosh-credentials/jumpbox_private_key
```

It would be ideal if the `GW` values had been stored with the `bosh alias-env` and were implicitly used whenever targeting the `-e bosh-lite-10` env

**Comment by cppforlife** [comment]
@drnic difficulty here is that i dont think bosh-cli should be saving sensitive material in ~/.bosh/config. 

in the example above, somehow you load in BOSH_ENVIRONMENT variable. from the same script you can use ssh-add to add jumpbox key. this leads to a more portable config, since this info isnt dependent on a particular machine.

one of the alternative approaches is to use github integration with openvpn-release to get on the network from where you can ssh. we use that for the bosh-ci.

**Comment by drnic** [comment]
Our bosh are already behind a VPN; my use of gateway is to access warden containers inside bosh-lites running on vsphere.

I’ll investigate ssh-adding the private key.

**Comment by shalako** [comment]
The CF Routing team upgraded our pipeline envs to latest bbl and now we've got a stupid jumpbox preventing me from connecting to the director. Is there some other credential I have to add to my ssh agent? 

I don't care at all about the security implications of storing sensitive data locally for development environments. I don't care. Please allow me to store all necessary data required to run commands against the director with the alias.
