### ISSUE TITLE
allow to alias directors with the same ip (different alias)

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-cli#367]

**Comment by evanfarrar** [comment]
I agree! The director's IP address is generally 10.0.0.6, in practice. Many users have struggled with this since BBL introduced jumpboxes and internal teams had to stop assuming their director had a unique IP. When we implemented tunnels, even the pair implementing it struggled to understand why their creds were wrong for about a day before discovering the feature worked on other machines and an alias for 10.0.0.6 was to blame.
