### ISSUE TITLE
should user be able to specify -v to override previous -v or to build an array

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/bosh-cli#372]

**Comment by evanfarrar** [comment]
@cppforlife and I had a discussion about this issue over hangouts, and he thought it would be nice to collect more input about it. I am mostly convinced this is not worth erroring about, but I wonder how others feel.

Frequently I encounter users who attempt to do something like the following:
```
bosh create-env bosh.yml -v vsphere_ds=diskarrayone -v vsphere_ds=diskarraytwo
```
or 
```
bosh deploy -d cf cf-deployment.yml -v system_domain=mysys.internalname.com -v system_domain=cf.mycompany.com 
```

The users expected to get TWO things, but instead, they overrode the first thing with the second thing. Sadness. Frustration.

Obviously, it is nice and good and intentional that you can override variables with other values. There are some power users that use xargs to supply var defaults then override them later in the same CLI invocation, but I do see people bump into this a lot. Perhaps we should warn or error when the same variable is supplied twice explicitly in a single invocation? Perhaps we could give powerusers a flag like `--ignore-var-errors` when they explicitly want the original behavior?

**Comment by cppforlife** [comment]
`-v vsphere_ds=diskarrayone` indicates to the cli that vsphere_ds is a string whereas i assume it's really an array. an alternative solution i see is we can add types for some variables that would indicate wherether values are arrays of something else. mismatching the type would make cli error out. wdyt?
