### ISSUE TITLE
Could support setup registry server on bosh client side without ssh_tunnel.

### ISSUE THREAD

**Issue by EdwardStudy** [cloudfoundry/bosh-cli#384]
Hi, I saw that 'generate registry config only when ssh_tunnel is specified' in: https://www.pivotaltracker.com/story/show/93032340

But I was confused that if we disable 'ssh login' on the stemcell, how could we ssh to director successfully.
I thought bosh-cli need allow to setup registry server without `ssh_tunnel` property when we need to use the registry to provide agent settings data.

Please tell me if I missed anything?
Thank you.:)

**Comment by dpb587-pivotal** [comment]
Hi - registry is used only on some IaaSes (e.g. AWS), and for those that require it, we tunnel the registry server to the VM via SSH (since most remote VMs would not be able to connect back to the workstation).

SSH access is still supported to VMs, however access is generally managed by BOSH director itself via `bosh ssh` command. When bootstrapping, and on some IaaSes, native SSH keys may still be supported for this reason.

For IaaSes which do not need registry (e.g. Google), `ssh_tunnel` should not be referenced in the configuration at all.

I hope this answers your questions.

**Comment by EdwardStudy** [comment]
@dpb587-pivotal Thank you so much. But I had a confusion about why we need ssh_tunnal if the registry support http or https access to bosh-agent. Did I miss something?

**Comment by dpb587-pivotal** [comment]
A `create-env`'d agent will try to connect to an HTTP server for the registry, yes. But, that registry server is started by the `create-env` process and running locally on the workstation. The only practical way to make sure the VM can reach that HTTP port running locally is by forwarding that port from inside the new VM onto the local workstation.

Does that explain?

**Comment by EdwardStudy** [comment]
@dpb587-pivotal This is it. Thank you a lot.
