### ISSUE TITLE
Deploy should support `--var-errs` and `--var-errs-unused`

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/bosh-cli#394]
Is there a reason for including the `--var-errs` and `--var-errs-unused` flags in `interpolate` but not `deploy`? I'd like to be able to fail a deploy if extra variables are passed. Happy to send in a patch if you'd be willing to add the feature.

**Comment by evanfarrar** [comment]
👍  I like this proposal (but am not a maintainer and can't speak to whether it would be merged).

I do see how interpolate is meant for checking and deploy is meant for doing it once you have checked, but I find it mega annoying anytime the two commands accept subtly different flags, because you have to type a significant number of args and would rather just edit the word "interpolate" to "deploy" and change nothing else once you've built up a working invocation.

**Comment by cppforlife** [comment]
@jmcarp any thoughts about how this relates to config server (which does get used by the deploy)?

**Comment by cppforlife** [comment]
@jmcarp how are you using these flags btw? which scenarios?
