### ISSUE TITLE
If $BOSH_ALL_PROXY set, please ignore `$HTTPS_PROXY`

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#401]
I need to set `$HTTPS_PROXY` for many Golang CLIs that cleverly use it to route traffic thru a SOCKS5 proxy. Can `bosh` move to use `HTTPS_PROXY` features from Golang 1.9/1.10? Or if we must keep `BOSH_ALL_PROXY`, can the CLI internally ignore `HTTPS_PROXY` if its set, please?

Currently, if both are set:

```
Fetching info:
  Performing request GET 'https://10.10.1.4:25555/info':
    Performing GET request:
      Retry: Get https://10.10.1.4:25555/info: http: error connecting to proxy http://socks5://localhost:9999: proxy: failed to parse port number:
```

**Comment by evanfarrar** [comment]
I have struggled with this matter now and again, but have become at peace with the current state of things with the two variables (you know of course, excepting the bug you are encountering). When I was looking at migrating a bunch of foundation teams to jumpboxes, the CF CLI was also implementing Go 1.9 proxy support, so I started to try to crib from them. Unfortunately, BOSH's proxy and HTTPS_PROXY have slightly different semantics:

- BOSH_ALL _PROXY is "a proxy for your the director"
- HTTPS_PROXY "a proxy for the internet"

Some Go CLIs have hijacked HTTPS_PROXY to mean "a gateway to the API endpoint." Unfortunately, the BOSH CLI talks to both an API endpoint (the director) and the internet at large to download releases mentioned in your manifest. So if you set HTTPS_PROXY and the gateway to your director is not also a gateway to the internet, then you are out of luck.

I think we could work around your bug here while still not making life harder for those with jumpboxes that lack egress:
1) people who need a proxy for the internet should set HTTPS_PROXY, we should assume _everything_ needs the proxy.
2) people who need a proxy for being routable to their director should set BOSH_ALL_PROXY, we can't assume their datacenter has egress, so all other CLI connections other than to the director API* should be unproxied
3) people who need both are too much of a headache for us to support and we will assume they meant to only set BOSH_ALL_PROXY and thoroughly ignore HTTPS_PROXY if BOSH_ALL_PROXY is set

*and any api that the director relies on, such as UAA, Credhub

**Comment by cppforlife** [comment]
> people who need a proxy for the internet should set HTTPS_PROXY, we should assume everything needs the proxy.

well, in some cases, going to the Director shouldnt go thru proxy, even though all other traffic goes through it.

**Comment by evanfarrar** [comment]
| well, in some cases, going to the Director shouldnt go thru proxy, even though all other traffic goes through it.
To support this usecase, it means you are missing a THIRD variable, like BOSH_NONE_PROXY or something. We can't implicitly have HTTPS_PROXY proxy everything but the BOSH endpoints.

**Comment by jpluscplusm** [comment]
Here's a tactical workaround in shell environments where both `HTTP[S]_PROXY` and `BOSH_ALL_PROXY` are set.

It applies only if you want *all* of the bosh CLI's traffic to obey the `BOSH_ALL_PROXY` setting, and to ignore `HTTP[S]_PROXY` entirely.

```
alias bosh='HTTP_PROXY= HTTPS_PROXY command bosh'
```

**Comment by frank-martens** [comment]
FYI: I ran into this issue while trying to use "bosh" and "cf" on the same machine 

bosh can't use HTTPS_PROXY and cf can't use the similar bosh proxy: 
`ssh+socks5://jumpbox@<<IP>>:22?private-key=/tmp/bosh-jumpbox628316669/bosh_jumpbox_private.key`

So I did a reverse alias... I export a variable called "cfproxy" with the needed proxy info for cf and then set:
`alias cf='HTTPS_PROXY=${cfproxy} command cf'`
