### ISSUE TITLE
bosh env output "User admin" is incorrect if authorizing with client/secret

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-cli#451]
```bash
BOSH_CA_CERT=-----BEGIN CERTIFICATE-----...
BOSH_ENVIRONMENT=192.168.50.6
BOSH_CLIENT=admin
BOSH_CLIENT_SECRET=secret

bosh env
```

The output starts correctly with `client 'admin'` but finishes incorrectly with `User      admin`:

```
Using environment '192.168.50.6' as client 'admin'

Name      bucc
UUID      9fc88b8f-27aa-42b1-9c45-7bf9aba5b242
Version   265.2.0 (00000000)
CPI       warden_cpi
Features  compiled_package_cache: disabled
          config_server: enabled
          dns: disabled
          snapshots: disabled
User      admin
```

Perhaps instead it should say:

```
User      n/a
Client    admin
```

There is no user logged in so I don't think the output should suggest there is.

```
$ ls ~/.bosh/config
ls: /Users/drnic/.bosh/config: No such file or directory
```

**Comment by dpb587-pivotal** [comment]
In this case, director returns the ID of the credential used to authenticate, which doesn't inherently indicate a username vs a client. I kind of like that it is simply an identifier, but I do agree "User" may imply a UAA user and cause confusion. Although, "Client" could also have confusion since that is often used to represent a generic API client, not necessarily authentication.

Perhaps there's a common term we could use instead? Would "Authentication" or "Identity" be any better to be able to show both values?
