### ISSUE TITLE
can bosh cli v1 handle the bosh links?

### ISSUE THREAD

**Issue by haohaoyingxin** [cloudfoundry/bosh-cli#485]
Hi,

BOSH links is bosh 2.0 feature, can bosh cli v1 used to create bosh-release for one app, in which one job's template erb file use the method bosh links?

Thanks!

**Comment by freddesbiens** [comment]
Hi @haohaoyingxin.

You can certainly use v1 of the CLI to create a release which will expose or consume links. This is because the CLI does not evaluate the links itself; this work is performed by the director.

Generally speaking, we recommend to use recent versions of the CLI. Is there any specific reason why you wish to use v1 of the CLI?

**Comment by freddesbiens** [comment]
I am closing this issue for now. Please re-open it if you need additional information.
