### ISSUE TITLE
Allow empty values in variable substitution

### ISSUE THREAD

**Issue by davidje13** [cloudfoundry/bosh-cli#489]
The check for empty values when loading variable substitutions seems unnecessary (https://github.com/cloudfoundry/bosh-cli/blob/master/director/template/var_kv.go#L26)

I found this after trying to specify a namespace for deployed app hostnames (e.g. myapp-dev, myapp-perf) where I still want to be able to use a non-namespaced name for acceptance (myapp).

The manifest contains `hostname: myapp((namespace))` and I'm setting the namespace (through concourse's CF plugin) as `vars.namespace: "-perf"` or `vars.namespace: ""`. But the blank string version triggers this error.

The only possible workarounds seem to be to namespace *all* deployments, or to use multiple manifests for each app.

**Comment by henrytk** [comment]
Same issue when I run `bosh interpolate --var="FOO="`. An empty string is a legitimate value, so I think this check is too strict.

**Comment by dpb587-pivotal** [comment]
The reason for the check is to avoid ambiguity on what an "empty" value means. For example, it could be nil, or an empty string, or an empty hash/array; and depending on where it is being referenced and used, empty string and nil could have different effect.

However, as a workaround, I would recommend you provide a "YAML" value. For example, you can do `-v namespace='""'` for an empty namespace (note the double quotation to ensure double quotes reaches `bosh` from the shell). Similarly, if someone wants a nil "empty" value, they could do `-v namespace=~`. This works since we attempt to parse the variable value as YAML.

I'm going to close this since we're not planning on making a change, but feel free to follow up if we can help clarify something further.
