### ISSUE TITLE
bosh deploy with error

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry/bosh-cli#491]
I have an existing CF deployment, and want to create a different CF deployment with name my-cf.
So I created similar cf manifest, change the name to my-cf , and use "bosh deploy"
I got errors such as:
- Uploading release 'binary-offline-buildpack/1.0.21':
      stat /var/vcap/cache/releases/binary-offline-buildpack-1.0.21-3468.55.0.tgz: no such file or directory

Can you let me know what this message means, and how to go about fixing it. -Thank you.

**Comment by aemengo** [comment]
Hi @betht1220 I suspect that you've used a manifest from `cfdev` as a reference. If so, you must edit the manifest to remove the `url:` from all entries in the releases section. This is because the cfdev manifest is expected to be run from within the VM where the releases are expected to be on the filesystem. See the picture below for reference:

<img width="1020" alt="screen shot 2018-11-04 at 8 55 55 pm" src="https://user-images.githubusercontent.com/4236888/47973830-79420c80-e074-11e8-8c0c-d292a70193a6.png">

**Comment by jaresty** [comment]
Closing this issue as it does not appear to be a problem with the bosh CLI.
