### ISSUE TITLE
Bosh CLI should support the same `NATs` certificate handling like BOSH Director

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh-cli#496]
For any deployment deployed with the BOSH Director there is no need for [`NATs` certificate configuration in the agent environment](https://github.com/cloudfoundry/bosh-deployment/blob/13cf7e11fba28c98f81f339008d67cea4f5a95d0/bosh.yml#L52-L65). The director [generates `NATs` certificate](https://github.com/cloudfoundry/bosh/blob/81f895c1bf4a445442919a0c2c01241d54f1fce9/src/bosh-director/lib/bosh/director/deployment_plan/steps/create_vm_step.rb#L100-L109) for each VM creation and adds them to the agent environment. That is how the agents get their `NATs` certificates. 

In the case of `create-env` you have to [specify the `NATs` certificate](https://github.com/cloudfoundry/bosh-deployment/blob/13cf7e11fba28c98f81f339008d67cea4f5a95d0/bosh.yml#L21) for the agent environment. This is inconsistent with the `deploy` workflow. The `create-env` should also generate `NATs` certificates and add them to the agent environment. So that there is no need to configure them.

**Comment by jaresty** [comment]
@beyhan Can you please open this issue against [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) since this isn't really an issue with the bosh CLI? Thanks!

**Comment by jaresty** [comment]
My bad - I misread the issue.  Reopening - sorry!

**Comment by beyhan** [comment]
This is more of a feature request. The request is about adding `NATs` certificate management to the `bosh-cli` for `create-env`. This will produce the same workflow as `deploy` and will remove the need to specify the NATs`variables` in the `manifest` for create-env

**Comment by aashah** [comment]
Hey,

The team, post-split, wants to have a quick discussion on how/whether we want to maintain parity between `create-env` and `deploy`. The discussion of v1 vs v2 deployment manifests is also playing a role here. We'll try and get back to you soon and see if we can come up with something together.

Aakash & @jaresty

**Comment by luan** [comment]
@beyhan, given there there is no director during `create-env` it's not feasible for us to completely remove the responsibility to pass around NATS certificates through the CLI. In theory we could make them implicit, but then we'd likely run into confusion around storing them on `vars-store`.

The middle ground I see here would be moving that property somewhere else in the manifest, but I don't see how that would be beneficial.

`create-env` is not really meant to be a 1:1 mapping with a `bosh deploy`, in fact, the flow of `create-env` is already quite different than `deploy` and it's not currently a priority for us to bridge that gap further at the moment.

I'm going to close this issue based on a conversation the team had and decided not to focus on this for the time being. If this comes back it'll likely be in the shape of a `create-env` overhaul, but that's not likely to happen in the short term.

If this issue is affecting you negatively, or blocking any stream of work for you, I'd be happy to have a chat and iron out anything we may have misunderstood. Cheers!

**Comment by beyhan** [comment]
@luan Thanks for the detailed answer. The decision is fair and I'm ok with it.
