### ISSUE TITLE
BOSH will always download 'bosh-dns-aliases' release during a deployment

### ISSUE THREAD

**Issue by aemengo** [cloudfoundry/bosh-cli#518]
No matter how many times I deploy cf-deployment (with no changes), the `bosh-dns-aliases` release keeps getting re-downloaded, no matter the IAAS. This is troublesome for deploys in offline environments.
Currently observed on [cf-deployment](https://github.com/cloudfoundry/cf-deployment): `v7.5.0`.

<img width="470" alt="screen shot 2019-02-21 at 8 15 34 am" src="https://user-images.githubusercontent.com/4236888/53186677-78a39680-35cf-11e9-8d30-007814c91e69.png">

**Comment by luan** [comment]
@aemengo I'm confused about how you'd even use cf-deployment in an offline environment since the manifest is defining URLs.

To echo what @dpb587-pivotal said:

> @heyjcollins, I'd recommend that cf-deployment stop trying to compile the bosh-dns-aliases release. It has no packages needing to be compiled (it's essentially a no-op export-release for you today), and I think it'd happen to fix this particular example, too.

You'd be able to get around this problem entirely if cf-deployment wasn't trying to do that.

Otherwise I'm throwing this into our prioritization queue as "As a bosh-cli user, I expect that compiled releases without packages aren't re-downloaded on every deploy".

CC @mgadiya
