### ISSUE TITLE
Bosh unalias-env command doesn't exist (but docs say it does)

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/bosh-cli#523]
[The bosh docs for `commands` says `unalias-env` should exist](https://bosh.io/docs/cli-v2/#unalias-env)

The last bosh-cli release [was 5.4.0](https://github.com/cloudfoundry/bosh-cli/releases/tag/v5.4.0) cut on november 13th.

[But the feature for unalias-env](https://github.com/cloudfoundry/bosh-cli/pull/409) was merged in on november 28th.

I realize this isn't a huge deal, just a heads up that the docs appear a little out of sync with what's actually available in the latest CLI release 👍

**Comment by luan** [comment]
Hi @aegershman, it looks like we missed a chance to release this recently. We're working on a couple small things on the CLI and should be releasing a new version pretty soon.

There's not much of an issue here since the code is already in place and we have plans to release a new version regardless. But feel free to re-open this if we for some reason end up failing to release.

CC @mgadiya (our product manager)

Cheers,
Luan
