### ISSUE TITLE
update-cloud-config does not offer the --named flag

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh-cli#542]
https://bosh.io/docs/cli-v2/#update-cloud-config does not support the `--name` flag. With this it cannot do everything that `update-config` can do. As mentioned in https://github.com/cloudfoundry/bosh/issues/2209#issuecomment-538312867 this should actually be the case.

**Comment by mfine30** [comment]
Hey @friegger I agree we should probably add that. It does feel like a good idea so that `update-runtime-config` and `update-cloud-config` match. That being said, I don't think `update-cloud-config` does anything special, so in theory `bosh update-config --name NAME --type cloud` would achieve the exact same result. 

I still see value in this change to help reduce surprises to operators, but not an urgent must have.

**Comment by mvach** [comment]
Hi I'm currently working on that issue.

The director part: https://github.com/cloudfoundry/bosh/tree/update-cloud-config-with-name-param
The cli part: https://github.com/cloudfoundry/bosh-cli/tree/update-cloud-config-with-name-param

I didn't create PRs so far, since there is some more testing that need to be done

**Comment by mvach** [comment]
I created:

- BOSH PR https://github.com/cloudfoundry/bosh/pull/2390
- BOSH-CLI PR https://github.com/cloudfoundry/bosh-cli/pull/600
