### ISSUE TITLE
Option to keep orphaned disks with clean-up --all

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh-cli#547]
When running clean-up without `--all` it keeps the 3 last versions of releases and stemcells. For stemcells that means for each mainline. This ultimately means that only running clean-up without --all piles up unneeded artefacts over time. In most cases we actually want to get rid of anything unused, but running `--all` also removes the orphaned disks. Orphaned disks we actually want to keep since there is already a mechanism in place which cleans them up after e.g. 5 days and deleting disks too eagerly is risky.

### Proposal

Three options:
1. Add a `--keep-orphaned-disks` option that can be additionally used with `--all`. This would keep the current behavior of `--all`, but allows to achieve what we need.
2. Add a `--include-orphaned-disks` and change `--all` to delete everything but the orphaned disks.
3. Just change `--all` to not remove the orphaned disks, since there is already a mechanism that deletes orphaned disks and one can also delete disks individually.

**Comment by h4xnoodle** [comment]
In order to avoid disrupting others' usage of clean-up, I think option 1 is best. 

The word 'all' with `--keep-orphaned-disks` is slightly odd, but I think for backwards compatibility and avoiding leaking disks for others is important.

Ideally I think option 3 with orphaned disks not even being included in `clean-up` would be great, but this would easily leak disks for those who don't update their automated clean up processes. `bosh disks --orphaned` and an option to delete all orphaned disks at once would be ideal. 

I'll go with the former option 1 for simplicity, despite a better design with option 3. This will solve the issue and avoid affecting others.

**Comment by h4xnoodle** [comment]
Corresponding director commit: https://github.com/cloudfoundry/bosh/commit/10e1778cd6ce151ca30855e280207003c235de76
