### ISSUE TITLE
Bosh runtime config has configuration dialog without meaning

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/bosh-cli#57]
**Old bosh:**
```
root@ruby-bosh:/tmp/build/8e72821d# bosh update runtime-config runtime-config.yml
Acting as user 'admin' on 'bosh'
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Error 530001: Runtime manifest contains the release 'myrelease' with version as 'latest'. Please specify the actual version string.
```

**New bosh:**
```
root@golang-bosh:/tmp/build/8e72821d# bosh-cli -e env update-runtime-config ./runtime-config.yml
Using environment '10.9.1.7' as '?'

Continue? [yN]:
```

Expected behavior would be to either not have `Continue` without a reason, such as showing a delta of the changes ala Concourse

**Comment by cppforlife** [comment]
Dup as #7. Feel free to continue discussion there. I definitely want us to add diff functionality for both of these commands.

**Comment by Murryy79** [comment]
i am seeing this same error.
ubuntu@pivotal-ops-manager:/tmp$ bosh -n deploy
Acting as client 'bosh_admin_client' on deployment 'prometheus' on 'p-bosh'
Getting deployment properties from director...
RSA 1024 bit CA certificates are loaded due to old openssl compatibility

Detecting deployment changes
----------------------------
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: '3363.29'
- alias: trusty
  os: ubuntu-trusty
  version: '3363.26'

releases:
- name: prometheus
  version: latest
- name: prometheus-custom
  version: latest

instance_groups:
- name: alertmanager
  jobs:
  - name: alertmanager
    properties:
      alertmanager:
        global:
          smtp_from: "<redacted>"
          smtp_require_tls: "<redacted>"
          smtp_smarthost: "<redacted>"
        env:
          http_proxy: "<redacted>"
          https_proxy: "<redacted>"

Deploying
---------

Director task 209373
  Started preparing deployment > Preparing deployment. Failed: Runtime manifest contains the release 'prometheus' with version as 'latest'. Please specify the actual version string. (00:00:00)

Error 530001: Runtime manifest contains the release 'prometheus' with version as 'latest'. Please specify the actual version string.

Task 209373 error

For a more detailed error report, run: bosh task 209373 --debug
ubuntu@pivotal-ops-manager:/tmp$


How do i resolve this error and successfully deploy?

Thanks..

**Comment by dpb587-pivotal** [comment]
@Murryy79, you should update your runtime config to specify an actual version for `prometheus` instead of using `latest` (e.g. `18.2.0`). The director is intentionally discouraging the behavior of using `latest` here because it would introduce ambiguity about which version was being used at a given time (since it could refer to latest as of upload time, or latest as of last deploy time).
