### ISSUE TITLE
SAML enabled UAA prohibits local account logins

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/bosh-cli#59]
If the BOSH UAA component has SAML configuration, there is no way to locally authenticate against UAA.  The workflow causes a `range prompts` call to set a UI `AskForPassword` which will require a not null entry.  Because the entry is not null, BOSH will force UAA to use SAML as the code was provided.

Users should be able to login with a local account, even in the presence of SAML.

**Comment by cppforlife** [comment]
+sree

interesting. 

this sounds like a security feature in uaa -- can only use one source of users. can you auth as local user via uaac when saml is on? 

even if not, cli follows prompts abstraction established by uaa (dunno and dont care what im asking, just collect user responses and forward them), so if uaa does allow auth from multiple sources (local and users) it should validate necessary prompts in the uaa server (so still transparent to bosh cli). ie  if saml field is empty assume its local user or something like that. or provide a better categorization of prompts so that cli can only show a subset.

**Comment by cppforlife** [comment]
Hi,

It depends on what UAA is configured for. It can support one or more
providers at the same time.
You can disable internal authentication through the property below:

uaa.disableInternalAuth:
description: "Disables internal user authentication"
default: false

Dmitriy is right about the UAA prompts. If internal auth is disabled we
don't send back the Username and Password prompts in the info response.


Thanks,
Sree Tummidi
Staff Product Manager
Identity - Pivotal Cloud Foundry

**Comment by sharms** [comment]
- UAA is configured for both SAML and internal authentication
- With both enabled, bosh-cli does not allow login to internal because of `AskForPassword`
- Ruby cli does not exhibit this behavior

**Comment by jmcarp** [comment]
Minor clarification--the ruby cli *does* incorrectly prompt for an otp when both saml and local accounts are enabled, but it's still possible to use local accounts because the ruby cli accepts empty strings for the otp. The golang cli doesn't accept empty strings here, so it's impossible to login in this situation.

**Comment by cppforlife** [comment]
> ...but it's still possible to use local accounts because the ruby cli accepts empty strings for the otp. The golang cli doesn't accept empty strings here, so it's impossible to login in this situation.

ah. nice find! sounds like we can fix that. it's using go-interact library: https://github.com/cloudfoundry/bosh-cli/blob/master/ui/ui.go#L101

**Comment by cppforlife** [comment]
@sharms @jmcarp if it's easy can you check if removing `interact.Required(...)` wrapper from two lines: [1], [2] allows you to log in?

[1] https://github.com/cloudfoundry/bosh-cli/blob/master/ui/ui.go#L104
[2] https://github.com/cloudfoundry/bosh-cli/blob/master/ui/ui.go#L132

**Comment by jmcarp** [comment]
@cppforlife: yep, allowing prompt values to be empty lets us log in again. I sent an example in #62.

**Comment by cppforlife** [comment]
Closed via PR#62. Next of version of CLI will have it.
