### ISSUE TITLE
Set the  the ACL when uploading to S3

### ISSUE THREAD

**Issue by albertvaka** [cloudfoundry/bosh-cli#592]
When `bosh create-release` and `bosh upload-blobs` push files to S3, they are non-public-readable by default. Should this CLI allow setting the ACL on those files to make them publicly readable?

**Comment by beyhan** [comment]
Hi @albertvaka,

could you please check the S3 configuration docs (https://bosh.io/docs/s3-release-blobstore/#bucket) we have. Is it an option for you as it is described in the docs to configure the S3 bucket so that the blobs are publicly available? BOSH just uses the S3 buckets to upload blobs and doesn't do any S3 configuration.
