### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [cloudfoundry/bosh-cli#651]
👋 it looks like the 7.5.7 release was not completed, ie the release did not get marked as latest release. Raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/171607

**Comment by rkoster** [comment]
@ystros could you take a look at this? According to @jpalermo you have context on this.

**Comment by ystros** [comment]
Thanks for the heads up!

It looks like the release job failed because a new commit had come in and the Concourse git resource `put` wasn't set up to only push tags. So it pushed the tags, succeeded, then tried to push the commit, which wasn't needed and failed.

I've re-run the job, and the release has finished publishing: https://github.com/cloudfoundry/bosh-cli/releases/tag/v7.5.7
