### ISSUE TITLE
Failed `bosh recreate` gives no user feedback

### ISSUE THREAD

**Issue by pronoiac** [cloudfoundry/bosh-cli#71]
Using `gobosh recreate` was a trial-and-error process. We specified the guid without the pool: 
1. The confirmation just mentioned the deployment, without any other info. 
2. No match was found; it ran through the package compilation, then didn't do anything. We weren't sure if it had quietly recreated the instance or if no action was taken.  

Example: 

```
→ gobosh --ca-cert deployments/bosh/certs/rootCA.pem -d cf-cfapps-io2 -e bosh.run.pivotal.io recreate not_a_valid_instance_GUID
Using environment 'xxx' as client 'concourse'

Using deployment 'cf-cfapps-io2'

Continue? [yN]: y

Task 1657663

20:14:02 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
20:14:02 | Preparing deployment: Preparing deployment (00:00:04)
20:15:25 | Preparing package compilation: Finding packages to compile (00:00:01)

Started  Fri Dec  9 20:14:02 UTC 2016
Finished Fri Dec  9 20:15:26 UTC 2016
Duration 00:01:24

Task 1657663 done

Succeeded
```

// cc @supertopher

**Comment by cppforlife** [comment]
> The confirmation just mentioned the deployment, without any other info.

Do you have suggestion what it should mention?

> No match was found..

This sounds like a problem with Director. I am somewhat surprised that it didnt fail. We'll take a look.

**Comment by tjvman** [comment]
The CLI is passing that UUID through to director as though it were an instance group name, which is fair for it to do.

However, once that gets into director, the parsing code in `src/bosh-director/lib/bosh/director/deployment_plan/deployment_spec_parser.rb:105` will see if the options hash has state overrides for any of the instance group names specified in the manifest - since the UUID it got from the CLI doesn't match, it will ignore the UUID key, and ultimately do a deployment update where no changes have been requested.

Seems like either director could validate that the keys in `@job_states` match some instance group name if present, or the CLI could output a mesage saying that the action was a no-op.

I suppose it's possible for the CLI to check with director to see if the positional args match any known instances, but that adds DB overhead.

@cppforlife @dpb587-pivotal wdyt

**Comment by mfine30** [comment]
Closing/re-opening to make tracker story

**Comment by aashah** [comment]
Hello, 

It looks like we have not responded to this in a reasonable time, and unfortunately a year has passed. Given this, we are going to close the issue, but please feel  free to re-open the issue. In doing so, a new Pivotal Tracker story will be generated, and we can revisit this.

Thanks again for submitting this, and apologies for closing without a proper resolution at this moment.

BOSH Systems Team - @aashah @luan @jaresty
