### ISSUE TITLE
Make it possible to reference anchors, defined in the manifest, from opsfile

### ISSUE THREAD

**Issue by s-matyukevich** [cloudfoundry/bosh-cli#83]
When I tried to do this I got the following error:

```
invalid argument for flag `-o, --ops-file' (expected []cmd.OpsFileArg): Deserializing ops file bosh-dns.yml': yaml: unknown anchor 'db' referenced
```

**Comment by cppforlife** [comment]
@s-matyukevich currently expected since anchors get resolved way before we get yaml objects. unfortunately (or fortunately) not much we can do besides documenting the behavior.

i would recommend though to consider using link as 99% of places where anchor is being used should probably be really a link.
